FROM node:14-alpine as builder

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the application code
COPY . .

# Build the application
RUN npm run build

# Stage 2 - Serve the production build with Nginx
FROM nginx:alpine

COPY --from=builder /app/build /usr/share/nginx/html

# Expose port 80 (adjust as needed)
EXPOSE 80

# Command to start Nginx
CMD ["nginx", "-g", "daemon off;"]
